name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        type: string
      build:
        description: "Build type"
        required: true
        type: choice
        default: "Android"
        options:
          # - All
          # - Binary
          - Android
          # - Apple
          # - app-store
          # - iOS
          # - macOS
          # - tvOS
          # - macOS-standalone
          # - publish-android
  push:
    branches:
      - main-next
      - dev-next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ inputs.build }}
  cancel-in-progress: true

jobs:
  calculate_version:
    name: Calculate version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.outputs.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Check input version
        if: github.event_name == 'workflow_dispatch'
        run: |-
          echo "version=${{ inputs.version }}" 
          echo "version=${{ inputs.version }}" >> "$GITHUB_ENV"
      - name: Calculate version
        if: github.event_name != 'workflow_dispatch'
        run: |-
          go run -v ./cmd/internal/read_tag --nightly
      - name: Set outputs
        id: outputs
        run: |-
          echo "version=$version" >> "$GITHUB_OUTPUT"
          
  # Commenting out the main build job as we're focusing only on Android
  # build:
  #   name: Build binary
  #   if: github.event_name != 'workflow_dispatch' || inputs.build == 'All' || inputs.build == 'Binary'
  #   runs-on: ubuntu-latest
  #   needs:
  #     - calculate_version
  # ... (rest of the build job)

  build_android:
    name: Build Android
    # Modified to always run when Android is selected (which is now the default)
    if: github.event_name != 'workflow_dispatch' || inputs.build == 'Android'
    runs-on: ubuntu-latest
    needs:
      - calculate_version
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28
      - name: Setup OpenJDK
        run: |-
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version
      - name: Set tag
        run: |-
          git ls-remote --exit-code --tags origin v${{ needs.calculate_version.outputs.version }} || echo "PUBLISHED=false" >> "$GITHUB_ENV"
          git tag v${{ needs.calculate_version.outputs.version }} -f
      - name: Build library
        run: |-
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Checkout main branch
        if: github.ref == 'refs/heads/main-next' && github.event_name != 'workflow_dispatch'
        run: |-
          cd clients/android
          git checkout main
      - name: Checkout dev branch
        if: github.ref == 'refs/heads/dev-next'
        run: |-
          cd clients/android
          git checkout dev
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}
      - name: Update version
        if: github.event_name == 'workflow_dispatch'
        run: |-
          go run -v ./cmd/internal/update_android_version --ci
      - name: Commit version changes
        if: github.event_name == 'workflow_dispatch'
        run: |-
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update version to ${{ needs.calculate_version.outputs.version }}" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
      - name: Update nightly version
        if: github.event_name != 'workflow_dispatch'
        run: |-
          go run -v ./cmd/internal/update_android_version --ci --nightly
      - name: Setup keystore
        run: |
          # Create local.properties with keystore passwords
          cat > clients/android/local.properties << EOF
          KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME=${{ secrets.ALIAS_NAME }}
          ALIAS_PASS=${{ secrets.ALIAS_PASS }}
          EOF
      - name: Build
        run: |-
          mkdir clients/android/app/libs
          cp libbox.aar clients/android/app/libs
          cd clients/android
          ./gradlew :app:assemblePlayRelease :app:assembleOtherRelease
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Prepare upload
        if: github.event_name == 'workflow_dispatch'
        run: |-
          mkdir -p dist/release
          cp clients/android/app/build/outputs/apk/play/release/*.apk dist/release
          cp clients/android/app/build/outputs/apk/other/release/*-universal.apk dist/release
      - name: Upload artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: binary-android-apks
          path: 'dist'

  # Commenting out the publish Android job as we're not publishing to Play Store
  # publish_android:
  #   name: Publish Android
  #   if: github.event_name == 'workflow_dispatch' && inputs.build == 'publish-android'
  #   runs-on: ubuntu-latest
  #   needs:
  #     - calculate_version
  # ... (rest of the publish_android job)

  # Commenting out the build_apple job as we're focusing only on Android
  # build_apple:
  #   name: Build Apple clients
  #   runs-on: macos-15
  #   needs:
  #     - calculate_version
  # ... (rest of the build_apple job)

  upload:
    name: Upload builds to GitHub releases
    # Ensure the job always runs for successful Android builds
    if: success() && (github.event_name == 'workflow_dispatch' && inputs.build == 'Android')
    runs-on: ubuntu-latest
    needs:
      - calculate_version
      - build_android
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - name: Setup Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: 2.5.1
          install-only: true
      - name: Cache ghr
        uses: actions/cache@v4
        id: cache-ghr
        with:
          path: |
            ~/go/bin/ghr
          key: ghr
      - name: Setup ghr
        if: steps.cache-ghr.outputs.cache-hit != 'true'
        run: |-
          cd $HOME
          git clone https://github.com/nekohasekai/ghr ghr
          cd ghr
          go install -v .
      - name: Set tag
        run: |-
          # Create a unique tag for each release
          git tag v${{ needs.calculate_version.outputs.version }} -f
          echo "VERSION=${{ needs.calculate_version.outputs.version }}" >> "$GITHUB_ENV"
      - name: Download builds
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Prepare release directory
        run: |-
          mkdir -p dist/release
          # Move all Android APKs to the release directory
          find dist -name "*.apk" -exec cp {} dist/release/ \;
      - name: Create GitHub release
        run: |-
          export PATH="$PATH:$HOME/go/bin"
          # Remove --replace flag to avoid overwriting existing releases
          ghr --draft --prerelease -p 5 "v${VERSION}" dist/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Add a separate job for automated builds from branches
  upload_nightly:
    name: Upload nightly builds to GitHub releases
    if: success() && contains(github.ref, '-next')
    runs-on: ubuntu-latest
    needs:
      - calculate_version
      - build_android
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - name: Setup ghr
        run: |-
          cd $HOME
          git clone https://github.com/nekohasekai/ghr ghr
          cd ghr
          go install -v .
      - name: Set tag
        run: |-
          echo "VERSION=${{ needs.calculate_version.outputs.version }}-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_ENV"
          git tag v${VERSION} -f
      - name: Download builds
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Prepare release directory
        run: |-
          mkdir -p dist/release
          # Move all Android APKs to the release directory
          find dist -name "*.apk" -exec cp {} dist/release/ \;
      - name: Create GitHub release
        run: |-
          export PATH="$PATH:$HOME/go/bin"
          ghr --draft --prerelease -p 5 "v${VERSION}" dist/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
